version: '2'
services:
    nginx:
        image: "${DOCKER_USER}/lnmp-nginx"
        build: ./nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - "${NGINX_ROOT}:/usr/share/nginx/html"
            - "${SHARE}:/share"
        networks:
            - frontend
        depends_on:
            - php
    php:
        image: "${DOCKER_USER}/lnmp-php"
        build: ./php-fpm
        volumes:
            - "${NGINX_ROOT}:/usr/share/nginx/html"
            - "${SHARE}:/share"
        networks:
            - frontend
            - backend
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        depends_on:
            - mysql
    mysql:
        image: "${DOCKER_USER}/lnmp-mysql"
        build: ./mysql
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - "${MYSQL_DATA}:/var/lib/mysql"
            - "${SHARE}:/share"
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
networks:
    frontend:
    backend:
